preset: psr12

risky: true

enabled:
  - blank_line_before_return
  - fully_qualified_strict_types
  - hash_to_slash_comment
  - include
  - method_separation
  - native_function_casing
  - no_duplicate_semicolons
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_trailing_comma_in_singleline_array
  - no_unused_imports
  - no_whitespace_before_comma_in_array
  - ordered_imports
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_simplified_null_return
  - phpdoc_property
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - print_to_echo
  - short_array_syntax
  - single_quote
  - spaces_cast
  - standardize_not_equal
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - whitespace_after_comma_in_array
