preset: psr2

risky: true

enabled:
  - binary_operator_spaces
  - blank_line_before_return
  - concat_with_spaces
  - fully_qualified_strict_types
  - function_typehint_space
  - hash_to_slash_comment
  - include
  - lowercase_cast
  - method_separation
  - native_function_casing
  - native_function_invocation
  - no_blank_lines_after_class_opening
  - no_blank_lines_between_uses
  - no_duplicate_semicolons
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_trailing_comma_in_singleline_array
  - no_unreachable_default_argument_value
  - no_unused_imports
  - no_whitespace_before_comma_in_array
  - nullable_type_declarations
  - ordered_imports
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_simplified_null_return
  - phpdoc_property
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - print_to_echo
  - short_array_syntax
  - short_scalar_cast
  - single_quote
  - spaces_cast
  - standardize_not_equal
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unary_operator_spaces
  - whitespace_after_comma_in_array
  - whitespacy_lines
